# Setup
title:               Jap치n
tagline:             
description:         'Kalandjaim Jap치nban'
url:                 https://hu.szabo.jp
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Szab칩 M치rk
  url:               https://twitter.com/torin42

# Gems
plugins:
  - jekyll-paginate

collections:
- images

# Custom vars
version:             1.1.0
